name: Docker Image CI

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/**"
      - "release/**"
      - "hotfix/**"
  pull_request:
    branches:
      - "main"
      - "develop"
      - "feature/**"
      - "release/**"
      - "hotfix/**"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker-compose -f docker-compose.yml up -d --build --console plain
        docker-compose -f docker-compose.yml exec php php -r "file_exists('.env') || copy('.env.example', '.env');"
        docker-compose -f docker-compose.yml exec php composer install
        docker-compose -f docker-compose.yml exec php php artisan migrate
        docker-compose -f docker-compose.yml exec php php artisan test

