name: Docker Image CI

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/**"
      - "release/**"
      - "hotfix/**"
  pull_request:
    branches:
      - "main"
      - "develop"
      - "feature/**"
      - "release/**"
      - "hotfix/**"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        echo ---Building and starting up docker---
        docker-compose -f docker-compose.yml up -d --build
        echo ---Containers up---


    - name: Copy .env
      run: |
        echo ---Copying .env---
        docker-compose -f docker-compose.yml exec -T php cat .env.example > .env
        echo ------Copied .env---------
      working-directory: sistema


    - name: Install dependencies
      run: |
        echo ---Installing dependencies---
        docker-compose -f docker-compose.yml exec -T php composer install
        echo ------Installed dependencies--------
      working-directory: sistema

    - name: Migrate DB
      run: |
        echo ---Migrating DB---
        docker-compose -f docker-compose.yml exec -T php php artisan migrate
        echo ------Migrated DB--------
      working-directory: sistema

    - name: Run phpunit tests
      run: |
        echo ---Testing application---
        docker-compose -f docker-compose.yml exec -T php php artisan test
        echo ------Everything OK!--------
      working-directory: sistema