name: Docker Image CI

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/**"
      - "release/**"
      - "hotfix/**"
  pull_request:
    branches:
      - "main"
      - "develop"
      - "feature/**"
      - "release/**"
      - "hotfix/**"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        echo ---Building and starting up docker---
        docker-compose -f docker-compose.yml up -d --build
        echo ---Containers up---


    - name: Copy .env
      run: |
        echo ---Copying .env---
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        echo ------Copied .env---------

    - name: Install dependencies
      run: |
        echo ---Installing dependencies---
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
        echo ------Installed dependencies--------

    - name: Migrate DB
      run: |
        echo ---Migrating DB---
        php artisan migrate
        echo ------Migrated DB--------

    - name: Run phpunit tests
      run: |
        echo ---Testing application---
        php artisan test
        echo ------Everything OK!--------